### ISSUE TITLE
Media Importing Failed

### ISSUE THREAD

**Issue by macthecoder** [awesomemotive/one-click-demo-import#131]
Hi,
For my Theme I've am using OCDI for importing contents (.xml) and widgets(.wie).
The theme was developed by a developer initially after got rejected from theme forest with some soft rejects it was handed me over for  making the issues fixed. Along with fixing the issues I've been changing some of the images from Demo contents.

What I've been facing after changing some of the images from Demo Content is it does not import any Medial files. But It import quite successfully the previous demo. See here: http://prntscr.com/i32cgb
![image](https://user-images.githubusercontent.com/25418332/35183467-1bf7f990-fe11-11e7-98d3-eb69f5bf12b8.png)

You can check both the xml files.
Previous: http://wp.codepixar.com/carnival/demodata/content.xml
Mine One: http://wp.codepixar.com/karnivel/demo/content.xml

Badly need any solution.
Thanks in advance.

**Comment by capuderg** [comment]
Hi,

what happens, if you try to import the new XML file with the default WP importer (wp-admin -> Tools -> Import -> WordPress) on the same site, that you tried to import with OCDI? 

You can reset the DB of that test page with a Reset WP DB plugin and then try with the default WP importer.

Let me know what happens.

Take care!

**Comment by macthecoder** [comment]
Hi,
I did what you have mentioned. But I got the same result.
![image](https://user-images.githubusercontent.com/25418332/35191121-b11f45d8-fe9c-11e7-8a67-620605b59556.png)
![image](https://user-images.githubusercontent.com/25418332/35191128-c43874a0-fe9c-11e7-92c5-3b73a5977c79.png)
![image](https://user-images.githubusercontent.com/25418332/35191132-d251b0ba-fe9c-11e7-841a-2b776d128a6c.png)
![image](https://user-images.githubusercontent.com/25418332/35191133-e1984c50-fe9c-11e7-8ee6-2078afa5a02a.png)

See the result on screenshots.
Firstly I have used WordPress's default importer got the same result then used WordPress Importer(v2) 
![image](https://user-images.githubusercontent.com/25418332/35191146-2e1843b4-fe9d-11e7-9be1-5e67ae45940e.png)
But got the same result.

**Comment by capuderg** [comment]
That indicates, that something is wrong with a server. It might be, that your server, where you have the test site, where you want to import to, does not allow to connect to your server where the images are hosted in order to download them.

Did you try the import on another server/hosting? Did you view your PHP logs, to see if there are any details to these failed downloads?

Take care!

**Comment by marceloquinze** [comment]
I believe it's because the images are served from localhost. I used to have the same issues when I started working with OCDI. Then I realised the problem was related to the fact that I was creating my whole demo on localhost and then trying to import it on a live site. 
It's impossible for a user to import an image that is hosted only on my local computer. I solved that when I moved my whole demo site to a remote host, and then generated my XML file from that live host. 
I believe the "problem" is on the wp:attachment_url XML tag. For example, for the canola2.jpg image you have this:

```
<wp:attachment_url>
<![CDATA[
http://localhost/karnivel/wp-content/uploads/2011/01/canola2.jpg
]]>
</wp:attachment_url>
```

The correct would be something like this:
```
<wp:attachment_url>
<![CDATA[
http://wp.codepixar.com/carnival/wp-content/uploads/2011/01/canola2.jpg
]]>
</wp:attachment_url>
```

Try to upload the images to a remote server, link them back to the posts and pages and generate the XML file once again. 
I believe this is not an OCDI related bug.
