### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by wpexplorer** [awesomemotive/one-click-demo-import#140]
Do you have anywhere one can donate to support this project?

Amazing work by the way, i've been dissecting the code all day ;) Nice use of WP_CLI and thanks for adding so many useful and crucial filters.

**Comment by primozcigler** [comment]
Hey, thanks a lot! Every time someone likes our project so much (s)he would like to donate, we throw a mini party here in the ProteusThemes HQ :confetti_ball: 

We don't have an official way of donating, mainly because we're a company and with EU bureaucracy that's a little bit complicated to do 'by the book'. However, on our Slack, we've agreed that because OCDI started as the experiment project by @capuderg and because he's been working on it now for years, many times also outside his regular working hours (which I never demanded, but it was his free will), providing support on the wp.org forums and in general contributed a lot of energy and time into this, you can donate him directly to his personal PayPal.

He'll paste his PayPal.me link here later today.

Cheers and thanks a lot! :heart:

**Comment by primozcigler** [comment]
Let's keep this 'issue' open :smiley:

**Comment by wpexplorer** [comment]
Thanks for the reply! I just realized I wasn't getting the email notices when people replied to my github threads.

And thank you @capuderg for all your hard work. If you are available for any freelance work as well, let us know ;)
