### ISSUE TITLE
Admin-ajax.php 404 issue

### ISSUE THREAD

**Issue by anteksiler** [awesomemotive/one-click-demo-import#151]
Some of our clients get 404 error with repeated calls to admin-ajax.php

I think it might be related to ModSecurity.

**Comment by capuderg** [comment]
Hi,

it's really hard to know, what the actual issue is with this cases. I would love to display a warning, for WP sites with PHP/server settings, which we know might cause issues, but first we need to know, what the actual issue is.

If you can debug it to a certain problem, we can improve the plugin.

There are also docs with common issues located here: https://github.com/proteusthemes/one-click-demo-import/blob/master/docs/import-problems.md

**Comment by anteksiler** [comment]
@capuderg Solution is given here, but not quite sure how it can be detected:
[https://deliciousbrains.com/wp-migrate-db-pro/doc/modsecurity/](url)

**Comment by capuderg** [comment]
Did you maybe test, by temporarily disabling the modsecurity on your clients server, to see, if this is causing the issues?

**Comment by capuderg** [comment]
Could you just verify with your customer, what exactly the problem was? Or did they tell you that the hosting disabled mod security and it worked then?

**Comment by anteksiler** [comment]
@capuderg apologies for the late reply, yes, ModSecurity was the issue.

**Comment by capuderg** [comment]
Hi,

sorry for not replying to this earlier (It looks like I missed the email about your previous message).

I'm no server expert, so I'm not comfortable implementing the edge case solutions, for detecting modsecurity, suggested on the internet, which work on some server configs and not on the other.

If there is a nice way to check for modSecurity and displaying a notice would work, then I'm up for it, but I wouldn't implement something, that can break the plugin on other server configs... Any PR are more than welcome.

Take care!
