### ISSUE TITLE
PHP Notice:  Array to string conversion in /wp-content/plugins/one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php on line 1848

### ISSUE THREAD

**Issue by Ataurr** [awesomemotive/one-click-demo-import#160]
I am trying to install demo content with the plugin and getting this error

PHP Notice:  Array to string conversion in /public_html/wp-content/plugins/one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php on line 1848

**Comment by capuderg** [comment]
Hi,

this is only a PHP notice and should not be causing you any real importing issues...

Does the import still complete till the end?

Take care!

**Comment by Ataurr** [comment]
No this is not working I am getting 500 internal server error.

**Comment by capuderg** [comment]
Hi,

the issue for internal server have to be somewhere else, because a PHP notice shouldn't cause it. A PHP error would, or maybe the server does not have as many resources and fails with a 500 server error?

Did you check your PHP error logs to see if there are some other errors there?

Take care!
