### ISSUE TITLE
I need to remove the demo

### ISSUE THREAD

**Issue by nadaarida** [awesomemotive/one-click-demo-import#171]
hello,

I tried the demo and it doesn't seem suitable for the website I am creating, I need to have it all removed but I can't. Please help!

Thanks.

**Comment by Ninetheme** [comment]
Hi

You can use WP Reset plugin, but be careful about your real content. If you want to remove all things, it is easy.

**Comment by capuderg** [comment]
Hi @nadaarida,

sorry for the late reply.

Our plugin does not delete any data, it just imports it. In order to delete all the imported data, you would have to manually delete all imported posts, pages, images, widgets,... There are plugins that reset the WP installation, but I'm 99% sure you don't want to do that since it will delete any existing content. That's why manually deleting the content you don't want is a longer but safer process.

Take care!
