### ISSUE TITLE
Wrong import Unicode characters

### ISSUE THREAD

**Issue by ghost** [awesomemotive/one-click-demo-import#179]
Hello Forks,
When xml file hase encoded Unicode characters like
`Ready to be taken aback by \u003cem\u003eawesome features.\u003c/em\u003e`
it become
`Ready to be taken aback by u003cemu003eawesome features.u003c/emu003e`
while I use default importer, the bug not happen.
Anyone here has bug like this?

**Comment by primozcigler** [comment]
Hi,

Thanks for reporting. Yes, this might be a bug. In our themes we don't use any special characters so I haven't noticed this. If you can provide a PR with a fix I'll be happy to merge it.

**Comment by gtusr11** [comment]
Hello,

Fix for this is in this pull request: https://github.com/proteusthemes/WordPress-Importer/pull/3

@primozcigler could you please merge it?

Details:
In content created with Gutenberg editor, some characters (used in block attribute) are encoded into unicode character codes that start with a backslash, e.g.
```
<!-- wp:plugin/custom-block {"data":"Some text and \u003ca href=\u0022https://example.com/\u0022\u003esome-link\u003c/a\u003e."} /-->
```
Before inserting into database, `wp_insert_post()` function runs the post object through `wp_unslash()` function which strips all backslashes. This breaks unicode character codes (and content). To mitigate that, we should run the post object through `wp_slash()` functions before passing it to `wp_insert_post()`. The original WordPress Importer does this.

**Comment by capuderg** [comment]
Hi @gtusr11,

thank you for preparing a PR for this issue.

We've just recently forked the https://github.com/proteusthemes/WordPress-Importer repo to: https://github.com/awesomemotive/WordPress-Importer and we'll be using this new one in the future updates for One Click Demo Import plugin.

If you want, you can open a PR there, but since it's a one-liner, I'll be able to add to the new repo no problem :)

I'll have to test this out first... Do you maybe have a small import XML file with unicode characters that I can use for testing?

Thank you again and have a nice day!

**Comment by capuderg** [comment]
The post and post meta data is now properly escaped with `wp_slash`.

This will be shipped in the next plugin update.
