### ISSUE TITLE
Tabs in excerpt content after import when using Gutenberg

### ISSUE THREAD

**Issue by yura-x** [awesomemotive/one-click-demo-import#181]
Hello! Thanks for your great plugin!
After exporting content from one installation to another (both using Gutenberg editor - WP version - 5.1) I found that there is no excerpt on blog feed. 
After digging the problem I found that post excerpt field on right hand side of Gutenberg editor contains several tab symbols (\t) and browser do not print them on frontend of course. If excerpt was blank (as it should be), then WordPress uses generated excerpt and then will be no problem.

**Comment by stylethemes** [comment]
Yes I'm also facing the same issue when importing the demo there is no excerpt in the blog posts it did happen also when using the classic editor in both installs this problem did start occurring after ver 5.0.3

with 5.0.3 installed the demo import show the excerpt anything after no excerpt and it doesn't matter if Gutenberg is installed or if the classic editor plugin is installed because I did test both of theme

**Comment by primozcigler** [comment]
Hi,

Thanks for reporting this. ATM I have no time to fix this issue and considering OCDI is a free plugin and we don't monetize it, I'll appreciate if anyone else will step in and provide a PR with a fix.

**Comment by yura-x** [comment]
Manual editing of XML file works for me.
I have replaced every instance of this:
```
 
<excerpt:encoded>
				<![CDATA[]]>		</excerpt:encoded>


```
to this:
```
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
```
and my problem was resolved.
@primozcigler - thanks for sharing your great plugin!

**Comment by marjesch** [comment]
yura-x, THANK YOU so MUCH for posting this.  I ran into the same problem with a huge site today.  Your solution saved me a boatload of time.  I'm SO grateful!

**Comment by capuderg** [comment]
Hi everyone,

sorry for the late reply.

I've just exported the content from a test site and all the empty excerpt fields exported to:
`<excerpt:encoded><![CDATA[]]></excerpt:encoded>`, so I didn't have the tabs in the exported file.

Was this may be an issue with the WP export functionality and was since fixed?

Does anyone still have this issue when exporting in WP?

I'll close this issue for now, but if new info is reported we'll investigate.

Thank you for reporting this problem and have a nice day!
