### ISSUE TITLE
Menu not set after import

### ISSUE THREAD

**Issue by STV11C** [awesomemotive/one-click-demo-import#184]
Hi, just wondering if anyone has experienced an issue with the 'menu' location not being set after import with an error msg?

I noticed the menu wasn't visible on frontend and navigating to Menus in WP admin the following error appears. **Notice: Trying to get property 'name' of non-object in /var/www/html/wp-admin/nav-menus.php on line 962
(Currently set to: )**

Strangely enough, when installing WP in English (United States) language set this issue doesn't occur, but installing WP in English (Australia) it occurs. I tested this several times to ensure it wasn't a fluke.

Any ideas? Thanks!

![Capture](https://user-images.githubusercontent.com/5532744/56849113-efdd0a00-6933-11e9-8c37-fa509cab25af.PNG)

**Comment by primozcigler** [comment]
Hi,

Thanks for reporting, but I can confirm that I haven't seen this issue anywhere yet. I assume that the problem must be with the import files or the hooks fired after import.

**Comment by capuderg** [comment]
Hi @STV11C,

sorry for the late reply.

If this is still relevant to you... The issue is, that the menu IDs are not guaranteed to be the same on every WP installation/import. The import wants to assign the menu locations to the IDs that were exported from the original WP site. This causes this notice/issue.

You would have to configure the  "manual" menu locations assignment in the after install hook. [Please read this FAQ item about how to do that](https://github.com/awesomemotive/one-click-demo-import#how-to-automatically-assign-front-page-posts-page-and-menu-locations-after-the-importer-is-done).

Have a nice day!

**Comment by STV11C** [comment]
Hi @capuderg 

Thanks for the reply! I forgot about this ticket but will check out the documentation link :)
Just checking if this WP plugin is getting continued support as it hasn't been updated for a while?
I have a page builder product that I was going to use this for - gutenize.com
It's on my list to get it working soon.

Cheers

**Comment by capuderg** [comment]
Hi @STV11C,

yes, this plugin is supported and there are some exciting plans for it, but I can't tell anything more than that :)

You will be using the OCDI in your plugin? If so and you plan to bundle the plugin code inside your plugin... Please prefix the code with your own namespace, so that it will not cause any conflicts when both plugins are active. If you'll require our plugin to be installed separately, then everything should be OK.

Have a nice day!
