### ISSUE TITLE
pt-ocdi/before_content_import returning old value for $selected_import

### ISSUE THREAD

**Issue by sanjeevpraja** [awesomemotive/one-click-demo-import#195]
I am trying to use pt-ocdi/before_content_import to import revolution slider before content is imported but $selected_import is returning old value. Any help?

**Comment by capuderg** [comment]
Hi @sanjeevpraja,

sorry for the late reply.

I've just tested a predefined demo import. I selected the second option, which means that the selected index is `1`. The first predefined demo import would have the value of `0`, the 3rd predefined demo import would have the value of `2` and so on...

Also if the demo import did not finish till the end in the previous try and you import the demo import again in a 6 minutes interval, it will pick up the previous unfinished demo data and it will try to finish it up.

So maybe you were testing with unfinished demo imports and that's why the previous data was there.

Let me know if this is still relevant to you and you are still experiencing this issue, I'm closing this issue for now.

Take care!
