### ISSUE TITLE
Partial import

### ISSUE THREAD

**Issue by ethanchoi812** [awesomemotive/one-click-demo-import#198]
HS Ticket: https://secure.helpscout.net/conversation/1013918349/0/?folderId=1536897

WordPress.org post: only 16 posts are importing and shows the message like (That's it, all done!. The demo import has finished.)

I have tried the plug-in on different servers with high configuration. But the result is the same. Is there any settings for importing all posts and pages (At least 50 posts).

User's issue: 

"only 16 posts are importing and shows the message like (That's it, all done!. The demo import has finished.) I have tried the plug-in on different servers with high configuration. But the result is the same. Is there any settings for importing all posts and pages (At least 50 posts)."

Here are the files they shared: http://cloud.supportally.com/39f7b07b2a94

**Comment by ethanchoi812** [comment]
Plugin config and WordPress posts export files from user: http://cloud.supportally.com/23112c43dc73

**Comment by ethanchoi812** [comment]
User says the initial issue with posts not being imported  is resolved https://secure.helpscout.net/conversation/1013418078/585245?folderId=1536897

They brought up a couple issues:

> I have used the plug-in "Easy Social Icons" (https://wordpress.org/plugins/easy-social-icons/). When I have import the demo content, I can't export and imports its settings. Is there any way to fix this issue?
> 
> I have used another plug-in "MC4WP: Mailchimp for WordPress" (https://wordpress.org/plugins/mailchimp-for-wp/). In this case, I can't export the plug-in settings, API, etc.

**Comment by capuderg** [comment]
Hey Ethan,

this looks like a server configuration issue on the client part, which we can't really control.

As for the issues with those two plugins I don't think our plugin could cause an issue with these two plugins not being able to import/export their settings. This plugin imports content (pages, posts, images, ...), widgets and customizer settings. It does not import plugin specific settings. Maybe he used some custom hooks to implement the import for those plugins, but that's outside of our scope.

I'll close this issue - it's been a while since this was reported, so I don't think it makes sense to contact the user now.

Take care!
