### ISSUE TITLE
MariaDB issue

### ISSUE THREAD

**Issue by anteksiler** [awesomemotive/one-click-demo-import#199]
Got the following bug report from a client:

> one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php

results to SQL syntax error. The table name is surrounded by '  in wordpress/wp-includes/wp-db.php on line 1357 

This syntax does not work in my mariadb 10.4.11

**Comment by capuderg** [comment]
Hi @anteksiler,

I'm sorry for this very late reply.

Do you maybe have some more information about this issue? The full error message and the trace stack of the code causing it?

Since this is an older issue I'll close it for now, but if some new information will come up, we'll reopen and investigate it.

Take care!
