### ISSUE TITLE
Providing multiple demos from an external Api endpoint

### ISSUE THREAD

**Issue by zamanq** [awesomemotive/one-click-demo-import#223]
I was wondering if it's possible to generate multiple demos by utilizing an external API endpoint instead of hadrcoding the import array every time I release a new demo.

array(
 'import_file_name'           => 'Demo Import 1',
.....rest of the fields
),
array(
'import_file_name'           => 'Demo Import 2',
....rest of the fields
),

to something like:
$all_demo = external_resource array;

foreach ( $all_demo as $demo ) {
return(
array(
 'import_file_name' =>$demo['import_file_name],
'import_file_url' => $demo['import_file_url'],
.....rest of the fields
),
)
}

Can you please demonstrate the idea into some working examples?

Thanks a bunch!

**Comment by capuderg** [comment]
Hi @zamanq,

of course, you can do that. I don't have any concrete examples of this working, but it should be possible.

In the `pt-ocdi/import_files` filter hook function you should pull in your "external resource" and then prepare/return the array with the structure that our plugin needs [more info here](http://awesomemotive.github.io/one-click-demo-import/#how-to-predefine-demo-imports).

I would also strongly suggest that you "cache" the results of this "external resource" in WP options (or transients) and update them only once a day. So that you don't make a request for this "external resource" on every page load from all your clients' sites...

Take care!
