### ISSUE TITLE
Problem Too many redirects

### ISSUE THREAD

**Issue by Unite2Me** [awesomemotive/one-click-demo-import#240]
hello, i use verve wp theme, if i try to click on plugin "One click demo import" i get white page with this message:
"too many redirects"

how i can fix this? 
I really dont know, my hosting check for me and they dont see nothing wrong in wp configuration and in my vps.

please help me..
thanks

**Comment by capuderg** [comment]
Hi @Unite2Me,

please contact your WP theme support and ask them to fix the `menu_slug` in one of our filters. They can find more information about this issue here: https://wordpress.org/support/topic/too-many-requests-pt-ocdi-plugin_page_setup-filter/

If you want to resolve it for you, you can edit the theme's code and find the `pt-ocdi/plugin_page_setup` filter and then make the suggested edit.

Thank you and have a nice day.
