### ISSUE TITLE
Post categories is not importing..

### ISSUE THREAD

**Issue by Khaledgy65** [awesomemotive/one-click-demo-import#241]
Hello, I used One  Click Demo Import plugin for my WordPress theme. I used Elementor as builder and made custom blog widgets. But when, I import demo data in a new WordPress site, all things import properly except categories and posts. They just show a specific category tech (as example). only. It happens on evry widgets where I use categories SELECT2 option. My theme has no bug for now. Why this is happening, I tried many times as fresh installation. It occurs in manually import too. Is this my category function problem or demo import issue..? I need Your help to much. I am sharing images and post widget. Please, help me. 

https://i.ibb.co/H7q3sk7/Screenshot-2.png
https://i.ibb.co/LZs8Sv7/Screenshot-1.png

My Elementor posts widget code:

https://pastebin.com/Dk8fcFBE
https://pastebin.com/cjH1j2pp

:

**Comment by capuderg** [comment]
Hi @Khaledgy65,

I think the issue is, that the term_id is different after the import. For example "Fashion" category has a term_id of 9 on your original WP site. But after you import your XML file on a fresh WP site, the term_id of that category will be 11 (just an example). The widget expects the term_id 9, but the category's new ID is 11.

You could use the term slug instead of the term_id and that will probably resolve that issue, because the slug won't change after the import.

OR I think you'll need to write some custom code, to update the widget with the new term_id in one of the "after import" hooks our plugin offers. I think you can use something similar to what we have for the custom menu widgets fix. Check the `fix_custom_menu_widget_ids` method in `inc/ImportActions.php`.

Take care!
