### ISSUE TITLE
Importing succeeds but no actual data is imported

### ISSUE THREAD

**Issue by RDKRACZ** [awesomemotive/one-click-demo-import#262]
![image](https://user-images.githubusercontent.com/43277609/173244720-581c0532-5141-4443-bf0a-1bedc196709e.png)
After clicking "Continue & Import" it instantly says "Import Complete!" and shows the green check mark without actually downloading anything.

**Comment by capuderg** [comment]
Hi @RDKRACZ,

could you please provide more information? The link to the theme? Which PHP and WP versions are you using?

Also, I would advise you, first to contact the theme support and see if they are aware of this issue with their theme data import? If our plugin does not report any issues, maybe the issue is with the import data (XML file).

Take care!
