### ISSUE TITLE
WordPress database error: [MySQL server has gone away]

### ISSUE THREAD

**Issue by etwordpress01** [awesomemotive/one-click-demo-import#270]
Hi, Hope you are doing great

We are theme development team and we would like to use this plugin in our themes, while integration, we are facing below issues

1) WordPress database error: [MySQL server has gone away]
2) It doesn't import Elementor settings
3) It doesn't set the home page
4) It doesn't set menus locations
5) It doesn't import our options table meta options
6) It took almost 30 minutes to complete the demo import process with 

Can anyone help regarding these issues

How we can solve that for the end users?

Thank you

**Comment by capuderg** [comment]
Hi,

I don't know about issue number 1 and I never seen a report of our plugin causing the MySQL DB error.

But for issue items 2 to 5, you would have to fix those issue with an "after import" hook and custom code. Please read more about it in [our documentation](https://ocdi.com/advanced-integration-guide/#after-import-custom-code-execution).

For issue number 6, the time to import depends on how many items you are importing and the items that take the longest are media files. If you have a lot of media files to import, I would suggest trying to reduce that number, so that your users will have faster imports.

Take care!
