### ISSUE TITLE
OCDI associates all posts with uncategorized term

### ISSUE THREAD

**Issue by Ontegor** [awesomemotive/one-click-demo-import#79]
OCDI plugin fails to remove the uncategorized term from the post which has at least one category set. 
Similarly here https://core.trac.wordpress.org/ticket/39301

**Comment by capuderg** [comment]
Hi,

thanks for reporting this... If you want this to be available in the plugin as soon as possible, you can create a pull request on our content importer repository and fix this issue: https://github.com/proteusthemes/WordPress-Importer

Otherwise I will take a look at this, but I can't tell you when that will be...

Take care!

**Comment by andyspw** [comment]
@Profit87 
It can be fixed with a hook. 

`
function your_prefix__processed_import_post( $post_id ) {
	wp_remove_object_terms( $post_id, 'uncategorized', 'category' );
}

add_action( 'wxr_importer.processed.post', 'your_prefix__processed_import_post', 10, 1 );
`
It removes 'uncategorized' term from all imported posts.

**Comment by capuderg** [comment]
I've tested this on a development branch (upcoming plugin update) and the "Uncategorized" category is not present for posts that have at least one category set.

Closing this GH issue.
