### ISSUE TITLE
Doesn't compile css after redux import

### ISSUE THREAD

**Issue by mxaGianluca** [awesomemotive/one-click-demo-import#98]
It seems that the Redux compiler action doesn't get triggered when you import a Redux config. I've resolved it by doing this manually in the 'after_import_setup' like this:

`$options = get_option('your-option-name');
redux_compiler_action($options);`

Shouldn't this be executed out of the box?

**Comment by capuderg** [comment]
Hi @mxaGianluca,

we do not use Redux framework in our themes, so I don't know how exactly the redux import should work.

I've added the Redux importer to our plugin because of many requests and once I've added it, there were no complaints about the functionality of our redux import.

What does `redux_compiler_action` do? Why is it needed?

Take care!

**Comment by tidalthemes** [comment]
@mxaGianluca I get a 500 error when doing so. Can you share your function where you ran it manually?
